### ISSUE TITLE
tests broken in master branch

### ISSUE THREAD

**Issue by chadxz** [balderdashy/sails-redis#40]
https://gist.github.com/chadxz/d80f8879ca94338d6d9e is my attempt to run the tests on master currently. Looks like the main difference between your last successful build on travis-ci and this run is that waterline-adapter-tests has been updated from 0.10.1 -> 0.10.4

I'll try to look into this more but it's a huge cache miss for me so it would probably take me a really long time to address this.

**Comment by dmarcelino** [comment]
:+1: 
Currently the waterline-adapter-tests are not running at all. Look at the build logs:
https://travis-ci.org/balderdashy/sails-redis/jobs/53945640#L207
Unfortunately it returns 0 so the build may still pass :confused:

**Comment by dmarcelino** [comment]
Added PR #64 to fix the integration tests.
@vanetix, @particlebanana please take a look at this, the current build results are misleading.

**Comment by Ryanc1256** [comment]
Fixed with PR #67
