### ISSUE TITLE
many to many does not work at all, multiple id in find

### ISSUE THREAD

**Issue by camel-chased** [balderdashy/sails-redis#54]
i have user - group relation
group have
`users:{
			collection:'User',
			dominant:true,
			via:'groups',
		},`
and user have
`groups:{
			collection:'Group',
			via:'users',
		},`

but when i want to use User.find(id).populate('groups') there is empty result in user.groups but in db everything is ok there are all records
in log I see that redis want to get something that doesn't exists `get  'groups:id:1,3'`
there is no such thing as `groups:id:1,3`
where is the problem?
the problem exists when adapter want to get more than one id like` where({id:[1,3]})` that resulting `get something:id:1,3`

**Comment by vanetix** [comment]
Fixed in 6f7464235a5b7a40ff2f5e47a915b9cb1f02dc9a

**Comment by Ryanc1256** [comment]
Fixed in PR #67 Closing.
