### ISSUE TITLE
Indexes/Uniques performing full database lookup

### ISSUE THREAD

**Issue by robgrimball** [balderdashy/sails-redis#65]
I am not sure if this is by design or if I am doing something wrong, but here is my case..

1)  I have a small model : 

    module.exports = {
        connection: 'redis',
        migrate: "alter",
        attributes: {
            dn: {type: 'string', required: true, unique: true, notNull: true, notEmpty: true},
            sAMAccountName: {type: 'string', unique: true}
       }
    };

2)  I insert a bunch of data via something that looks like this : 

     LdapEntry.create(ldapUser).then(function(data) {
         ...
     });

3)  I search for an entry later in that data via something that looks like this : 

     LdapEntry.find()
         .where({'dn': entry.dn})
         .then(function(dataArray) {
                 sails.log.info("data.dn:", dataArray[0].dn);
          });

I have redis set up with monitor to see what is going on, and whenever I get around to the search, it is getting every single item in the collection, then doing it's search in sails-redis presumably for the one item that matches, and then sending that item back.  While this works, I had expected that the unique: true's set in the model would create keys by which sails-redis would look up the data, rather than grabbing the entire collection.

I did a key * on the database however and saw that it was only creating primary (id) keys for the data, and nothing to support lookups by key in the model's unique attributes (dn & sAMAccountName).

I am trying to figure out if this is simply the design of sails-redis and expected, or if I am failing to do something to get it to make the keys I want it to and of course to use them after they are made.  

I did notice that if I add an item that was already in the collection that it detects it already exists quickly, but that is through the fact that it is creating "sets" for the unique attributes, which only tell it quickly whether or not the key exists already, not seemingly giving any indication where to find it.

So is this simply the way it is supposed to work?  Or am I doing something (or not doing something) wrong?  Or is this a bug?  I am using redis 3.0.0 if that matters.  Their latest stable build.

Thanks!

**Comment by Ryanc1256** [comment]
So pretty much a the current time what the key structure look's like is

waterline:tableName:primaryKey
  > waterline:tableName:primaryKey:primaryKeyValue

and so on, it has some more but they are mainly used for auto increment the id's and keeping what everything is called.

So there isn't really any "clean" or "simple" way of making a quick look up system for keys that aren't primary indexes, it will have to look through all the keys in that table to do a search.

Hope this help's.

**Comment by robgrimball** [comment]
Yes, I eventually figured out what was going on looking at the code in the adapter.  And it is as you say, seemingly unable to get the data via any sort of redis key/value lookups other than the primary autogenerated waterline id.  This does sort of obviate the whole purpose of redis to a large extent and I wonder why have a redis adapter if you can't do fast key/value lookups with it, but I also understand why this is the case, since waterline's lookups have to be much more flexible than a simple key/value pair lookup(ie, being able to sort, filter, perform many more operations on an index than a simple lookup).  

To make this adapter more useful however, it would seem some ability to determine when the find operation is being performed can be served out via one of the alternate key/value stores (non-waterline ID) and to use that alternate lookup method in those cases would bring a big part of the power of Redis to the actual sails-redis adapter.  Of course, there is still the pub/sub model in redis that is not tapped from what I can tell as well, but that is another story.

Anyway, what we ended up doing was reworking our code to be a mongo datastore, and it works sufficiently even if it would be nicer to have redis.  I will close this issue however, as the question is answered and understood as to what is happening now and why it is done this way.

**Comment by Ryanc1256** [comment]
Yeah I understand where your wanted to go with this, but trying to keep with waterline and trying to keep with only using one key/value pair it makes it hard to go with any other data structure.

It's good that you got it working in the end!.
