### ISSUE TITLE
when Redis fails to connect, the `waterline.initialize` callback is not triggered with an error

### ISSUE THREAD

**Issue by catdad** [balderdashy/sails-redis#87]
Issue first mention here: https://github.com/balderdashy/sails-redis/issues/86

For example, this happens when initalizing the `sails-redis` module with incorrect config or the Redis server is not running.

I checked the `sails-postgresql` and `sails-mongo` adapters, and they both provide a `ECONNREFUSED` error to the callback. Postgresql even has a longwinded explanation of the possible issues (not really required here).

**Comment by Ryanc1256** [comment]
@catdad lovely thank you, ill see how they do it so we can keep the consistency between the adapters

**Comment by catdad** [comment]
I successfully got it working when, in the same error handling code as #86, I called the callback for ECONNREFUSED errors. The caveat is that you have to make sure nothing else triggers the callback. Currently, the `redis` module will keep retrying, and if you get a connection eventually, it will fire the `ready` event, and therefore the callback. Also, if there is any other error, the error handler will again fire. It's simple to work around, but I am wondering if it would be best to actually tear down the `redis` instance and assume it cannot be used.

I have to assume that they implemented the retry thing for a reason, but I can't quite figure out what that might be.

I can submit a PR now, but it just feels to dirty at the moment.

**Comment by Ryanc1256** [comment]
yeah, that is true it will try to reconnect automatically...

I wonder if we want to do something like a default "max_attempts" and set it to 1, that will assure that the connection wont retry it again and the error event wont call again, but then again some people might like it like that, so i wonder if they set up a max_attempts in the config, it will over-ride the default so it will retry the error connection and if it keeps calling the error message then it's there problem kind of thing.

this would be less hacky and when ECONNREFUSED does occur we can just call the callback with an error

**Comment by catdad** [comment]
Yeah, that was going to be my next attempt, but I ran out of time today.

It seems fine to me to set the default `max_attempts` to 1. It makes sense in my app, anyway. However, for backwards compatibility, it might be shady to change that. I am perfectly fine setting that to 1 in my options (as far as I can tell, it will just pass that along to the redis module), as long as callback errors are hooked up.

Perhaps the callback should trigger after the `max_attempts` value is reached... not sure if redis handles that in a pretty way.

**Comment by catdad** [comment]
@Ryanc1256 I worked it out so that there are no breaking changes for anyone who relies on the current behavior. By default, it will still attempt to reconnect indefinitely and never call the callback with an error. However, when `max_attempts` is set (to 1, or any other value), and `redis` module exits before the ready event is fired and an error has occurred in that time, it will trigger the callback.

See https://github.com/balderdashy/sails-redis/pull/88

**Comment by catdad** [comment]
Any idea on when to expect the merged code here and on #86 to be published to NPM?

**Comment by catdad** [comment]
This was published in `0.10.7`
