### ISSUE TITLE
SSL/TLS connection config

### ISSUE THREAD

**Issue by tomcelinski** [balderdashy/sails-redis#94]
How do you configure sails-redis to access a redis instance on a hosted server over SSL/TLS

**Comment by irlnathan** [comment]
Howdy @tomcelinski, StackOverflow would be a better platform for this question. Thanks!

Also, if you can think of ways we could improve the docs here to help clarify this, please let us know via an issue or pull request in sails-docs (the content for http://sailsjs.org is pulled from that repo).
