### ISSUE TITLE
How do I use sails-redis with a Redis cluster?

### ISSUE THREAD

**Issue by kpturner** [balderdashy/sails-redis#97]
If I create a redis cluster, as described here: http://redis.io/topics/cluster-tutorial
how do I then make use of that cluster with sails-redis?

**Comment by Ryanc1256** [comment]
@kpturner currently we don't support it, due to the limitations of the backing redis connectors we are using...

https://github.com/NodeRedis/node_redis/issues/1040

They have it on there road map, but it's not added yet.... once they support it then we can.

**Comment by kpturner** [comment]
OK thanks - So I need to use sails-ioredis instead (for now)?

**Comment by Ryanc1256** [comment]
@kpturner well if you really want clusters then you cant do it yet... so you may just have to use non-cluster or find another thing that will let you do that

**Comment by kpturner** [comment]
Sentinel is another option and sails-ioredis supports that so I will look into that option some more. Thanks for the clarification.

**Comment by Salakar** [comment]
@kpturner bit late to the party here, but a while back i created https://github.com/Salakar/sails-ioredis - a sails adapter for `ioredis` if you're looking for cluster support.

**Comment by kpturner** [comment]
OK thanks

**Comment by Salakar** [comment]
I replied on https://github.com/Salakar/sails-ioredis/issues/1 - cluster support added now, thanks.
